# Generated by Django 4.0.4 on 2022-07-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=250, verbose_name='Subscription Id')),
                ('company_id', models.CharField(max_length=250, verbose_name='Company Id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subscription Details',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=21, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('profile_image', models.FileField(blank=True, default='profile_logo.jpg', null=True, upload_to='users/profile', verbose_name='Profile Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Company Name')),
                ('company_group', models.CharField(max_length=250, verbose_name='Company Group')),
                ('landmark_and_location', models.CharField(max_length=500, verbose_name='Landmark & Location')),
                ('city', models.CharField(max_length=350, verbose_name='City')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('state', models.CharField(max_length=350, verbose_name='State')),
                ('country', models.CharField(max_length=350, verbose_name='Country')),
                ('company_phone_number', models.CharField(max_length=50, verbose_name='Company Phone #')),
                ('company_email', models.CharField(max_length=250, verbose_name='Compnay Email')),
                ('primary_contact_name', models.CharField(max_length=250, verbose_name='Primary Contact Name')),
                ('primary_contact_email', models.CharField(max_length=250, verbose_name='Primary Contact Email')),
                ('primary_contact_phone_number', models.CharField(max_length=50, verbose_name='Primary Contact Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
