# Generated by Django 4.0.4 on 2022-07-31 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_adsconfigurations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriptionDetails',
            new_name='SubscriptionsDetails',
        ),
    ]
