# Generated by Django 4.0.4 on 2022-07-31 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_subscriptiondetails_subscriptions_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.CreateModel(
            name='PackageApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('Surveyscaled', 'Surveyscaled'), ('TestScaled', 'TestScaled'), ('User Registration Landing Page', 'User Registration Landing Page'), ('Download Landing Page', 'Download Landing Page'), ('E-commerce Site Management', 'E-commerce Site Management'), ('Price Pormotion Landing Page', 'Price Pormotion Landing Page'), ('Video Landing Page', 'Video Landing Page'), ('Donation Landing Page', 'Donation Landing Page'), ('Event Registration Landing Page', 'Event Registration Landing Page')], max_length=150)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.subscriptionpackages')),
            ],
        ),
    ]
