# Generated by Django 4.0.4 on 2022-07-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscriptionpackages_alter_company_table_packageapps'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsdetails',
            name='subscription_plan',
            field=models.CharField(default=1, max_length=150, verbose_name='Subscription Plan'),
            preserve_default=False,
        ),
    ]
