# Generated by Django 4.0.4 on 2022-07-12 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmailDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comapny_name', models.CharField(max_length=250, verbose_name='Company Name')),
                ('comapny_address', models.CharField(max_length=500, verbose_name='Company Address')),
                ('comapny_city', models.CharField(max_length=50, verbose_name='City')),
                ('comapny_city_zip', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('company_country', models.CharField(max_length=100, verbose_name='Country')),
                ('survey_invite_subject', models.CharField(max_length=250, verbose_name='Survey Invitation Email Subject')),
                ('survey_invite_message', models.CharField(max_length=1000, verbose_name='Survey Invitation Email Message')),
            ],
            options={
                'verbose_name_plural': 'Company Details',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_no', models.AutoField(primary_key=True, serialize=False, verbose_name='Survey #')),
                ('name', models.CharField(max_length=1000, verbose_name='Survey Name')),
                ('survey_purpose', models.CharField(max_length=5000, verbose_name='Survey Purpose')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('is_active', models.BooleanField(default=True)),
                ('total_reponses', models.IntegerField(default=0)),
                ('company_id', models.CharField(max_length=150, verbose_name='Company Id')),
                ('subscription_id', models.CharField(max_length=150, verbose_name='Subscription Id')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, verbose_name='Slug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Surveys',
                'ordering': ['-survey_no'],
            },
        ),
        migrations.CreateModel(
            name='Survey_Metas',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Survey #')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('total_reponses', models.IntegerField(default=0)),
                ('survey_name', models.CharField(max_length=500, verbose_name='Survey Name')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Survey_Metas',
                'ordering': ['-survey_id'],
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_id', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Gender')),
                ('age', models.CharField(choices=[('Under 18', 'Under 18'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65 or Above', '65 or Above')], max_length=20, verbose_name='Age')),
                ('children_under_eighteen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, verbose_name='Children Under 18')),
                ('number_of_children', models.IntegerField(blank=True, default=0, null=True)),
                ('martial_status', models.CharField(choices=[('Single, Not Married', 'Single, Not Married'), ('Married', 'Married'), ('Living with partner', 'Living with partner'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Prefer not to answer', 'Prefer not to answer')], max_length=50, verbose_name='Marital Status')),
                ('employement_status', models.CharField(choices=[('Employed full time', 'Employed full time'), ('Employed half time', 'Employed half time'), ('Unemployed', 'Unemployed')], max_length=50, verbose_name='Employement Status')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Question ID')),
                ('question_no', models.CharField(max_length=50, verbose_name='Question #')),
                ('question_statement', models.CharField(max_length=5000, verbose_name='Question Statement')),
                ('question_type', models.CharField(choices=[('Yes/No Question', 'Yes/No Question'), ('Scaled Question', 'Scaled Question'), ('Scaled Question - Customer Satisfaction Survey', 'Scaled Question - Customer Satisfaction Survey'), ('Scaled Question - Net Promoter Survey', 'Scaled Question - Net Promoter Survey'), ('Multiple Choices - Select One Answer', 'Multiple Choices - Select One Answer'), ('Multiple Choices - Select All That Applies', 'Multiple Choices - Select All That Applies'), ('Free Form', 'Free Form')], max_length=50, verbose_name='Question Type')),
                ('scale_type', models.CharField(blank=True, choices=[('1-10', '1-10 Worst to Best'), ('1-5', '1-5 Worst to Best'), ('1-4', '1-4 Worst to Best')], max_length=20, null=True, verbose_name='Scale Type')),
                ('number_of_answers', models.IntegerField(blank=True, null=True, verbose_name='Number of Answers')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Last Update Date')),
                ('survey_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_survey', to='surveyscaled.survey', verbose_name='Survey #')),
            ],
            options={
                'verbose_name_plural': "Survey's Questions",
                'ordering': ['-survey_no'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestionAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Answer ID')),
                ('answer_statement', models.CharField(max_length=5000, verbose_name='Question Statement')),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_question', to='surveyscaled.surveyquestions', verbose_name='Question #')),
                ('survey_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers_survey', to='surveyscaled.survey', verbose_name='Survey #')),
            ],
            options={
                'verbose_name_plural': "Survey Question's Answers",
                'ordering': ['-survey_no'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(max_length=50, verbose_name='Question #')),
                ('question_statement', models.CharField(max_length=1000, verbose_name='Question Statement')),
                ('responder_id', models.CharField(max_length=250, verbose_name='Responder Id')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answer Date')),
                ('question_answer', models.CharField(max_length=250, verbose_name='Question Answer')),
                ('question_type', models.CharField(max_length=50, verbose_name='Question Type')),
                ('survey_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_num', to='surveyscaled.survey', verbose_name='Survey #')),
            ],
            options={
                'verbose_name_plural': 'Survey Answers',
                'ordering': ['-survey_no'],
            },
        ),
        migrations.CreateModel(
            name='Survey_Metas_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_value', models.CharField(max_length=50, verbose_name='Select Value')),
                ('is_target', models.CharField(max_length=1, verbose_name='Is Target')),
                ('target_value', models.CharField(blank=True, max_length=2, null=True, verbose_name='Target Value')),
                ('is_demographics', models.CharField(max_length=1, verbose_name='Is_Demographics')),
                ('is_freeform', models.CharField(max_length=1, verbose_name='Is_FreeForm')),
                ('question_id', models.CharField(blank=True, default=uuid.uuid4, max_length=40, unique=True, verbose_name='Question #')),
                ('question', models.CharField(max_length=1000, verbose_name='Question')),
                ('abbreviation', models.CharField(max_length=150, verbose_name='Abbreviation')),
                ('question_type', models.CharField(choices=[('Demographics', 'Demographics'), ('Free Form', 'Free Form'), ('Scaled Answers', 'Scaled Answers'), ('Multiple Choice - Select one', 'Multiple Choice - Select one'), ('Select All that Applies', 'Select All that Applies')], max_length=40, verbose_name='Question Type')),
                ('survey_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_meta_number', to='surveyscaled.survey_metas', verbose_name='Survey #')),
            ],
            options={
                'verbose_name_plural': 'Survey Meta Questions',
                'ordering': ['-survey_no'],
            },
        ),
        migrations.CreateModel(
            name='Survey_Metas_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_id', models.CharField(max_length=250, verbose_name='Responder Id')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answer Date')),
                ('question_date', models.DateField()),
                ('question_statement', models.CharField(max_length=1000, verbose_name='Question Statement')),
                ('question_answer', models.CharField(max_length=25, verbose_name='Question Answer')),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reference', to='surveyscaled.survey_metas_questions', verbose_name='Question #')),
                ('survey_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_metas_detail', to='surveyscaled.survey_metas', verbose_name='Survey #')),
            ],
            options={
                'verbose_name_plural': 'Survey_Metas_Answers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvs')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('survey_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_number', to='surveyscaled.survey', verbose_name='Survey #')),
            ],
            options={
                'verbose_name_plural': 'Email CSV Files',
                'ordering': ['-id'],
            },
        ),
    ]
