# Generated by Django 4.0.4 on 2022-07-08 15:39

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='landing_page_two/about_us/')),
            ],
            options={
                'verbose_name_plural': 'About Us Info',
            },
        ),
        migrations.CreateModel(
            name='any_product_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Discount_percentage', models.IntegerField()),
                ('Promotional_deals_Coupon_Code', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='landing_page_two/promotional_deals_img')),
            ],
            options={
                'verbose_name_plural': 'Any Product Discount',
            },
        ),
        migrations.CreateModel(
            name='app_2_website_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='landing_page_two/logo/')),
            ],
            options={
                'verbose_name_plural': 'Website Logo (Webapp-2)',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField()),
                ('Phone', models.CharField(max_length=255)),
                ('Mail', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Our Contact Info',
            },
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='coupon_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=255)),
                ('Discount_rate', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Coupon Rate',
            },
        ),
        migrations.CreateModel(
            name='Get_In_Touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'GET IN TOUCH',
            },
        ),
        migrations.CreateModel(
            name='Home_Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_one', models.CharField(max_length=255)),
                ('Title_two', models.CharField(max_length=255)),
                ('banner', models.ImageField(upload_to='landing_page_two/Banners/')),
            ],
            options={
                'verbose_name_plural': 'Home Banner',
            },
        ),
        migrations.CreateModel(
            name='loyalty_benefit_info_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Benefit Info Table',
            },
        ),
        migrations.CreateModel(
            name='Our_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='landing_page_two/Blogs/')),
                ('Date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Our Blogs',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=2000)),
                ('product_price', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='landing_page_two/product_image')),
                ('image2', models.ImageField(blank=True, default='', null=True, upload_to='landing_page_two/product_image')),
                ('image3', models.ImageField(blank=True, default='', null=True, upload_to='landing_page_two/product_image')),
                ('image4', models.ImageField(blank=True, default='', null=True, upload_to='landing_page_two/product_image')),
                ('image5', models.ImageField(blank=True, default='', null=True, upload_to='landing_page_two/product_image')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_store.categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.CreateModel(
            name='Stripe_Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Publishable_key', models.CharField(max_length=255)),
                ('Secret_key', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'STRIPE API',
            },
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Specific_Level_Product_Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount_percentage', models.IntegerField()),
                ('Promotional_deals_Coupon_Code', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_store.products')),
            ],
            options={
                'verbose_name_plural': 'Specific Level Product Discount',
            },
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.CharField(max_length=1)),
                ('review_text', models.TextField()),
                ('review_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_store.products')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=1000)),
                ('product_details', models.TextField()),
                ('total_bill', models.CharField(max_length=1000)),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=1000)),
                ('street', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('zip', models.CharField(max_length=1000)),
                ('ordered', models.BooleanField(default=False)),
                ('order_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Your_order_has_been_packed', models.BooleanField(default=False)),
                ('Your_order_is_on_the_way', models.BooleanField(default=False)),
                ('Delivered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='loyalty_registration_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(default='', max_length=255)),
                ('Phone_No', models.CharField(default='', max_length=255)),
                ('Email_id', models.CharField(default='', max_length=255)),
                ('Discount_percentage', models.IntegerField()),
                ('loyality_Coupon_Code', models.CharField(max_length=255)),
                ('Coupon_rate', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ecommerce_store.coupon_rate')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Registration Table',
            },
        ),
        migrations.CreateModel(
            name='EmailConfirmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=500)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Email-Confirmed',
            },
        ),
        migrations.CreateModel(
            name='Category_level_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount_percentage', models.IntegerField()),
                ('Promotional_deals_Coupon_Code', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='landing_page_two/promotional_deals_img')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_store.categories')),
            ],
            options={
                'verbose_name_plural': 'Category Level Discount',
            },
        ),
    ]
