# Generated by Django 4.0.4 on 2022-07-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='any_product_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Discount_percentage', models.IntegerField()),
                ('Promotional_deals_Coupon_Code', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='promotional_deals_img')),
            ],
            options={
                'verbose_name_plural': 'Any Product Discount',
            },
        ),
        migrations.CreateModel(
            name='Category_level_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=255)),
                ('Discount_percentage', models.IntegerField()),
                ('Promotional_deals_Coupon_Code', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='promotional_deals_img')),
            ],
            options={
                'verbose_name_plural': 'Category Level Discount',
            },
        ),
        migrations.CreateModel(
            name='Get_In_Touch_app_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'GET IN TOUCH App-3',
            },
        ),
        migrations.CreateModel(
            name='social_media_app_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Media App-3',
            },
        ),
        migrations.CreateModel(
            name='Specific_Level_Product_Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('Discount_percentage', models.IntegerField()),
                ('Promotional_deals_Coupon_Code', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Specific_promotional_deals_img')),
            ],
            options={
                'verbose_name_plural': 'Specific Level Product Discount',
            },
        ),
        migrations.CreateModel(
            name='subscribe_app_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Subscribers App-3',
            },
        ),
        migrations.CreateModel(
            name='website_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='landing_page_two/logo/')),
            ],
            options={
                'verbose_name_plural': 'Website Logo (Webapp-3)',
            },
        ),
    ]
