# Generated by Django 4.0.4 on 2022-07-08 16:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_7_website_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='landing_page_seven/logo/')),
            ],
            options={
                'verbose_name_plural': 'Website Logo (Webapp-7)',
            },
        ),
        migrations.CreateModel(
            name='Get_In_Touch_app_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'GET IN TOUCH App-7',
            },
        ),
        migrations.CreateModel(
            name='Landing_page_seven_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_First_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_Last_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_Email_Address', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_country_Address', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_checked_or_not', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Landing page seven model',
            },
        ),
        migrations.CreateModel(
            name='Landing_page_seven_model_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_full_image', models.ImageField(blank=True, null=True, upload_to='landing_page_seven/full_image/')),
                ('Model_left_content_top', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Model_content_image', models.ImageField(blank=True, null=True, upload_to='landing_page_seven/content_image/')),
                ('Model_left_content_bottom', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Landing page seven model left side',
            },
        ),
        migrations.CreateModel(
            name='social_media_app_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Media App-7',
            },
        ),
        migrations.CreateModel(
            name='subscribe_app_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Subscribers App-7',
            },
        ),
    ]
