# Generated by Django 4.0.4 on 2022-07-08 16:51

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_8_website_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='landing_page_eight/logo/')),
            ],
            options={
                'verbose_name_plural': 'Website Logo (Webapp-8)',
            },
        ),
        migrations.CreateModel(
            name='Get_In_Touch_app_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'GET IN TOUCH App-8',
            },
        ),
        migrations.CreateModel(
            name='Landing_page_eight_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_First_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_Last_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_Email_Address', models.CharField(blank=True, max_length=256, null=True)),
                ('Model_checked_or_not', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Landing page eight model',
            },
        ),
        migrations.CreateModel(
            name='Landing_page_eight_model_left',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_left_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Model_full_image', models.ImageField(blank=True, null=True, upload_to='landing_page_eight/full_image/')),
                ('Model_left_video', models.FileField(blank=True, null=True, upload_to='landing_page_eight/left_video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
            options={
                'verbose_name_plural': 'Landing page one model left side',
            },
        ),
        migrations.CreateModel(
            name='social_media_app_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Social Media App-8',
            },
        ),
        migrations.CreateModel(
            name='subscribe_app_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Subscribers App-8',
            },
        ),
    ]
